### ISSUE TITLE
Error decoding JSON

### ISSUE THREAD

**Issue by plugngeek** [hugoaf/joomla-to-grav-exporter#1]
Hi,

I have an error when i want to export data : 

Error decoding JSON data: unexpected end of data

Joomla 3.7.2

**Comment by haviladev** [comment]
Just tested in Joomla 3.7.2 with no issues.

Are you testing the "master" or "nested categories" branch?, php version?

Would you share your php error log?,  or configure your Joomla error reporting to maximum or development and paste here errors.

**Comment by plugngeek** [comment]
I update my PHP version and try again (php 5.5.9 right now)
